services:
  db:
    image: mysql:8.0
    container_name: ecommerce-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ecommerce_db
      MYSQL_ROOT_PASSWORD: root
    command: --lower_case_table_names=1
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
