import pandas as pd
import random
from faker import Faker
import os
from datetime import datetime, timedelta

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATASET_DIR = os.path.join(BASE_DIR, 'Dataset')

fake = Faker('en_US')

PASSWORD_HASH = "$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4c0J9bE3cUq6rWq."

MAX_PRODUCTS = 200
MAX_ORDERS = 500
MAX_REVIEWS = 1000

random.seed(42)

def escape_str(s):
    if pd.isna(s): return "''"
    s = str(s).replace('\\', '\\\\').replace("'", "''")
    if len(s) > 500:
        s = s[:500]
    return f"'{s}'"

def clean_price(x):
    try:
        val = str(x).replace('₹', '').replace(',', '').replace('"', '').strip()
        val = val.replace('\xa0', '').replace(' ', '')
        return float(val) if val else 0.0
    except:
        return 0.0

def clean_date(date_str):
    try:
        if pd.isna(date_str): return None
        return pd.to_datetime(date_str).strftime('%Y-%m-%d %H:%M:%S')
    except:
        return None

def map_status(status):
    s = str(status).lower().strip()
    if s in ['complete', 'completed', 'delivered']:
        return 'DELIVERED'
    elif s in ['shipped', 'shipping']:
        return 'SHIPPED'
    elif s in ['confirmed', 'processing']:
        return 'CONFIRMED'
    elif s in ['canceled', 'cancelled']:
        return 'CANCELLED'
    elif s in ['refunded', 'refund']:
        return 'REFUNDED'
    else:
        return 'PENDING'

def generate_db_script():
    sql_lines = []
    
    def append_sql(line):
        sql_lines.append(line)
    
    append_sql("-- ============================================")
    append_sql("-- DATABASE INITIALIZATION SCRIPT")
    append_sql("-- Generated by etl_pipeline.py")
    append_sql("-- ============================================")
    append_sql("")
    
    append_sql("-- ============================================")
    append_sql("-- 0. CREATE TABLES")
    append_sql("-- ============================================")
    
    append_sql("""CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role_type VARCHAR(50) NOT NULL,
    phone VARCHAR(50),
    address_street VARCHAR(255),
    address_city VARCHAR(100),
    address_state VARCHAR(100),
    address_zip_code VARCHAR(20),
    address_country VARCHAR(100),
    preferences TEXT,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_login_at DATETIME,
    INDEX idx_users_email (email),
    INDEX idx_users_role_type (role_type)
);""")
    
    append_sql("""CREATE TABLE IF NOT EXISTS Customer_Profiles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    age INT,
    city VARCHAR(100),
    membership_type VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
    INDEX idx_customer_profiles_user_id (user_id)
);""")
    
    append_sql("""CREATE TABLE IF NOT EXISTS Stores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    owner_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES Users(id) ON DELETE CASCADE,
    INDEX idx_stores_owner_id (owner_id)
);""")
    
    append_sql("""CREATE TABLE IF NOT EXISTS Categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    parent_id INT,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    description TEXT,
    FOREIGN KEY (parent_id) REFERENCES Categories(id) ON DELETE SET NULL,
    INDEX idx_categories_parent_id (parent_id)
);""")
    
    append_sql("""CREATE TABLE IF NOT EXISTS Products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    store_id INT NOT NULL,
    category_id INT NOT NULL,
    sku VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(500) NOT NULL,
    description TEXT,
    unit_price DECIMAL(10,2) NOT NULL,
    stock_quantity INT NOT NULL DEFAULT 0,
    FOREIGN KEY (store_id) REFERENCES Stores(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES Categories(id) ON DELETE CASCADE,
    INDEX idx_products_store_id (store_id),
    INDEX idx_products_category_id (category_id)
);""")
    
    append_sql("""CREATE TABLE IF NOT EXISTS Orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    store_id INT NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at DATETIME NOT NULL,
    grand_total DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (store_id) REFERENCES Stores(id) ON DELETE CASCADE,
    INDEX idx_orders_user_id (user_id),
    INDEX idx_orders_store_id (store_id)
);""")
    
    append_sql("""CREATE TABLE IF NOT EXISTS Order_Items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES Orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES Products(id) ON DELETE CASCADE,
    INDEX idx_order_items_order_id (order_id),
    INDEX idx_order_items_product_id (product_id)
);""")
    
    append_sql("""CREATE TABLE IF NOT EXISTS Shipments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    warehouse VARCHAR(255),
    mode VARCHAR(100),
    status VARCHAR(100),
    tracking_number VARCHAR(100),
    estimated_delivery_date DATE,
    FOREIGN KEY (order_id) REFERENCES Orders(id) ON DELETE CASCADE,
    UNIQUE INDEX idx_shipments_order_id (order_id)
);""")
    
    append_sql("""CREATE TABLE IF NOT EXISTS Reviews (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    star_rating INT NOT NULL,
    content TEXT,
    admin_reply TEXT,
    reply_created_at DATETIME,
    created_at DATETIME,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES Products(id) ON DELETE CASCADE,
    INDEX idx_reviews_user_id (user_id),
    INDEX idx_reviews_product_id (product_id)
);""")
    
    append_sql("""CREATE TABLE IF NOT EXISTS Store_Settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    store_id INT NOT NULL,
    email VARCHAR(255),
    category VARCHAR(100),
    description TEXT,
    currency VARCHAR(10),
    timezone VARCHAR(50),
    FOREIGN KEY (store_id) REFERENCES Stores(id) ON DELETE CASCADE,
    UNIQUE INDEX idx_store_settings_store_id (store_id)
);""")
    
    append_sql("""CREATE TABLE IF NOT EXISTS SystemSettings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    setting_key VARCHAR(255) UNIQUE NOT NULL,
    setting_value VARCHAR(500) NOT NULL,
    description TEXT
);""")
    
    append_sql("""CREATE TABLE IF NOT EXISTS AuditLogs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    actor VARCHAR(255) NOT NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100),
    entity_id INT,
    severity VARCHAR(50) NOT NULL,
    created_at DATETIME NOT NULL,
    metadata TEXT,
    INDEX idx_audit_logs_actor (actor),
    INDEX idx_audit_logs_entity (entity_type, entity_id),
    INDEX idx_audit_logs_created_at (created_at)
);""")
    
    append_sql("")
    append_sql("-- ============================================")
    append_sql("-- 1. CLEAR EXISTING DATA")
    append_sql("-- ============================================")
    append_sql("SET FOREIGN_KEY_CHECKS = 0;")
    append_sql("TRUNCATE TABLE AuditLogs;")
    append_sql("TRUNCATE TABLE SystemSettings;")
    append_sql("TRUNCATE TABLE Store_Settings;")
    append_sql("TRUNCATE TABLE Reviews;")
    append_sql("TRUNCATE TABLE Shipments;")
    append_sql("TRUNCATE TABLE Order_Items;")
    append_sql("TRUNCATE TABLE Orders;")
    append_sql("TRUNCATE TABLE Products;")
    append_sql("TRUNCATE TABLE Categories;")
    append_sql("TRUNCATE TABLE Stores;")
    append_sql("TRUNCATE TABLE Customer_Profiles;")
    append_sql("TRUNCATE TABLE Users;")
    append_sql("SET FOREIGN_KEY_CHECKS = 1;")
    append_sql("")
    
    append_sql("-- ============================================")
    append_sql("-- 1. USERS (Fixed 10 + 40 generated = 50 total)")
    append_sql("-- ============================================")
    
    users = []
    existing_users = [
        (1, 'Admin User', 'admin@test.com', 'ADMIN'),
        (2, 'Corporate User', 'corp@test.com', 'CORPORATE'),
        (3, 'User One', 'user1@test.com', 'INDIVIDUAL'),
        (4, 'User Two', 'user2@test.com', 'INDIVIDUAL'),
        (5, 'Cory Watson', 'corp5@test.com', 'CORPORATE'),
        (6, 'Austin Patterson', 'corp6@test.com', 'CORPORATE'),
        (7, 'Kenneth Harrington', 'corp7@test.com', 'CORPORATE'),
        (8, 'Robert Macdonald', 'corp8@test.com', 'CORPORATE'),
        (9, 'Casey Vang', 'corp9@test.com', 'CORPORATE'),
        (10, 'Teresa Meza', 'samantha00@example.net', 'INDIVIDUAL'),
    ]
    
    for u in existing_users:
        users.append((u[0], u[1], u[2], PASSWORD_HASH, u[3], 'ACTIVE'))
    
    corporate_names = [
        'Alex Thompson', 'Maria Garcia', 'James Wilson', 'Sarah Chen', 'Michael Brown',
        'Emily Davis', 'David Miller', 'Lisa Anderson', 'Robert Taylor', 'Jennifer Martinez'
    ]
    
    for i in range(10):
        uid = 11 + i
        name = corporate_names[i]
        email = f"{name.lower().replace(' ', '.')}@test.com"
        users.append((uid, name, email, PASSWORD_HASH, 'CORPORATE', 'ACTIVE'))
    
    individual_names = [
        'John Smith', 'Emma Johnson', 'William Brown', 'Olivia Davis', 'Benjamin Miller',
        'Sophia Wilson', 'Lucas Moore', 'Ava Taylor', 'Mason Anderson', 'Isabella Thomas',
        'Ethan Jackson', 'Mia White', 'Alexander Harris', 'Charlotte Martin', 'Daniel Thompson',
        'Amelia Garcia', 'Matthew Robinson', 'Harper Clark', 'Joshua Rodriguez', 'Evelyn Lewis'
    ]
    
    for i in range(20):
        uid = 21 + i
        name = individual_names[i]
        email = f"{name.lower().replace(' ', '.')}@example.com"
        users.append((uid, name, email, PASSWORD_HASH, 'INDIVIDUAL', 'ACTIVE'))
    
    for u in users:
        created = (datetime.now() - timedelta(days=random.randint(30, 365))).strftime('%Y-%m-%d %H:%M:%S')
        append_sql(f"INSERT INTO Users (id, name, email, password_hash, role_type, status, created_at) VALUES ({u[0]}, {escape_str(u[1])}, '{u[2]}', '{u[3]}', '{u[4]}', '{u[5]}', '{created}');")
    
    append_sql("")
    append_sql("-- ============================================")
    append_sql("-- 2. CUSTOMER PROFILES")
    append_sql("-- ============================================")
    
    cities = ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana', 'Gaziantep', 'Konya', 'Mersin', 'Diyarbakir',
              'Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya']
    membership_types = ['BASIC', 'SILVER', 'GOLD', 'PLATINUM']
    
    profile_id = 1
    for i, u in enumerate(users):
        if u[4] == 'INDIVIDUAL':
            age = random.randint(22, 65)
            city = random.choice(cities)
            membership = random.choice(membership_types)
            append_sql(f"INSERT INTO Customer_Profiles (id, user_id, age, city, membership_type) VALUES ({profile_id}, {u[0]}, {age}, {escape_str(city)}, '{membership}');")
            profile_id += 1
    
    append_sql("")
    append_sql("-- ============================================")
    append_sql("-- 3. STORES (Corporate owners: 2, 5-14)")
    append_sql("-- ============================================")
    
    store_names = [
        'TechZone Electronics', 'Fashion Hub', 'Home & Garden Plus', 'Sports World',
        'Books & Media Center', 'Electronics Pro', 'Fashion Outlet', 'Home Essentials',
        'Active Life Store', 'Media Mart'
    ]
    
    corp_owner_ids = [2] + list(range(5, 15))
    
    for i, (store_name, owner_id) in enumerate(zip(store_names, corp_owner_ids)):
        append_sql(f"INSERT INTO Stores (id, owner_id, name, status) VALUES ({i+1}, {owner_id}, {escape_str(store_name)}, 'ACTIVE');")
    
    append_sql("")
    append_sql("-- ============================================")
    append_sql("-- 4. CATEGORIES")
    append_sql("-- ============================================")
    
    main_categories = [
        'Electronics', 'Fashion', 'Home & Garden', 'Sports', 'Books',
        'Health & Beauty', 'Toys', 'Food & Beverages', 'Automotive', 'Office Supplies'
    ]
    
    cat_id = 1
    categories = {}
    
    for cat_name in main_categories:
        append_sql(f"INSERT INTO Categories (id, name, parent_id, status, description) VALUES ({cat_id}, {escape_str(cat_name)}, NULL, 'ACTIVE', {escape_str(f'{cat_name} products')});")
        categories[cat_name] = cat_id
        cat_id += 1
    
    sub_categories = {
        'Electronics': ['Smartphones', 'Laptops', 'Headphones', 'Cameras', 'Accessories'],
        'Fashion': ["Men's Clothing", "Women's Clothing", 'Shoes', 'Accessories', 'Jewelry'],
        'Home & Garden': ['Furniture', 'Kitchen', 'Garden Tools', 'Decor', 'Bedding'],
        'Sports': ['Fitness', 'Outdoor', 'Team Sports', 'Water Sports', 'Camping'],
        'Books': ['Fiction', 'Non-Fiction', 'Educational', 'Children Books', 'Magazines'],
        'Health & Beauty': ['Skincare', 'Vitamins', 'Makeup', 'Fragrances', 'Personal Care'],
        'Toys': ['Board Games', 'Action Figures', 'Dolls', 'Educational Toys', 'Outdoor Toys'],
        'Food & Beverages': ['Organic', 'Snacks', 'Beverages', 'Cooking Ingredients', 'Supplements']
    }
    
    for main_cat, sub_cats in sub_categories.items():
        parent_id = categories.get(main_cat, 1)
        for sub_cat in sub_cats:
            append_sql(f"INSERT INTO Categories (id, name, parent_id, status, description) VALUES ({cat_id}, {escape_str(sub_cat)}, {parent_id}, 'ACTIVE', {escape_str(f'{sub_cat} from {main_cat}')});")
            cat_id += 1
    
    append_sql("")
    append_sql("-- ============================================")
    append_sql("-- 5. PRODUCTS (from amazon.csv)")
    append_sql("-- ============================================")
    
    products_db = []
    prod_id = 1
    
    try:
        df_products = pd.read_csv(os.path.join(DATASET_DIR, 'amazon.csv'))
        df_products = df_products.dropna(subset=['product_name']).head(MAX_PRODUCTS)
        
        used_categories = list(categories.keys())
        
        for idx, row in df_products.iterrows():
            if prod_id > MAX_PRODUCTS:
                break
            
            cat_str = str(row.get('category', 'Electronics'))
            main_cat = cat_str.split('|')[0] if '|' in cat_str else cat_str.split('&')[0]
            
            if main_cat not in categories and used_categories:
                main_cat = random.choice(used_categories)
            
            cat_id = categories.get(main_cat, 1)
            
            price = clean_price(row.get('discounted_price', 0))
            if price <= 0:
                price = clean_price(row.get('actual_price', 0))
            if price <= 0:
                price = random.uniform(9.99, 4999.99)
            
            name = str(row.get('product_name', f'Product {prod_id}'))[:490]
            desc = str(row.get('about_product', fake.sentence()))[:500]
            
            sku = f"SKU-{fake.ean(length=8)}-{prod_id}"
            stock = random.randint(0, 500)
            store_id = random.randint(1, 10)
            
            append_sql(f"INSERT INTO Products (id, store_id, category_id, sku, name, description, unit_price, stock_quantity) VALUES ({prod_id}, {store_id}, {cat_id}, '{sku}', {escape_str(name)}, {escape_str(desc)}, {price:.2f}, {stock});")
            products_db.append({'id': prod_id, 'store_id': store_id, 'price': price, 'stock': stock})
            prod_id += 1
            
    except Exception as e:
        print(f"Error reading amazon.csv: {e}")
    
    append_sql("")
    append_sql("-- ============================================")
    append_sql("-- 6. ORDERS (from Pakistan Ecommerce Dataset)")
    append_sql("-- ============================================")
    
    orders_db = []
    order_id = 1
    
    indiv_user_ids = [3, 4, 10] + list(range(21, 41))
    
    try:
        df_orders = pd.read_csv(os.path.join(DATASET_DIR, 'Pakistan Largest Ecommerce Dataset.csv'), low_memory=False)
        df_orders = df_orders.dropna(subset=['increment_id']).head(MAX_ORDERS)
        
        for idx, row in df_orders.iterrows():
            if order_id > MAX_ORDERS:
                break
            
            user_id = random.choice(indiv_user_ids)
            store_id = random.randint(1, 10)
            
            status = map_status(row.get('status', 'complete'))
            
            days_ago = random.randint(1, 730)
            date_str = (datetime.now() - timedelta(days=days_ago)).strftime('%Y-%m-%d %H:%M:%S')
            
            try:
                qty = int(row.get('qty_ordered', 1))
                if qty <= 0: qty = 1
            except:
                qty = 1
            
            try:
                total = clean_price(row.get('grand_total', 0))
                if total <= 0:
                    total = clean_price(row.get('price', 0)) * qty
            except:
                total = random.uniform(50, 5000)
            
            append_sql(f"INSERT INTO Orders (id, user_id, store_id, status, created_at, grand_total) VALUES ({order_id}, {user_id}, {store_id}, '{status}', '{date_str}', {total:.2f});")
            orders_db.append({'id': order_id, 'user_id': user_id, 'store_id': store_id, 'grand_total': total})
            order_id += 1
            
    except Exception as e:
        print(f"Error reading Pakistan dataset: {e}")
    
    append_sql("")
    append_sql("-- ============================================")
    append_sql("-- 7. ORDER ITEMS")
    append_sql("-- ============================================")
    
    oi_id = 1
    for order in orders_db:
        num_items = random.randint(1, 5)
        for _ in range(num_items):
            if products_db:
                product = random.choice(products_db)
                qty = random.randint(1, 3)
                append_sql(f"INSERT INTO Order_Items (id, order_id, product_id, quantity, price) VALUES ({oi_id}, {order['id']}, {product['id']}, {qty}, {product['price']:.2f});")
                oi_id += 1
    
    append_sql("")
    append_sql("-- ============================================")
    append_sql("-- 8. SHIPMENTS")
    append_sql("-- ============================================")
    
    shipment_id = 1
    warehouses = ['Istanbul Central', 'Ankara North', 'Izmir West', 'Bursa East', 'Antalya South']
    modes = ['STANDARD', 'EXPRESS', 'OVERNIGHT']
    
    for order in orders_db:
        if order['id'] % 3 != 0:
            status = 'DELIVERED' if random.random() > 0.3 else 'IN_TRANSIT'
            warehouse = random.choice(warehouses)
            mode = random.choice(modes)
            tracking = f"TRK{random.randint(10000000, 99999999)}"
            
            try:
                order_date = datetime.strptime(
                    [r for r in sql_lines if r.startswith(f"INSERT INTO Orders (id, user_id, store_id, status, created_at, grand_total) VALUES ({order['id']}")][0].split("'")[7],
                    '%Y-%m-%d %H:%M:%S'
                )
            except:
                order_date = datetime.now() - timedelta(days=random.randint(1, 30))
            
            delivery_date = order_date + timedelta(days=random.randint(3, 14))
            
            append_sql(f"INSERT INTO Shipments (id, order_id, warehouse, mode, status, tracking_number, estimated_delivery_date) VALUES ({shipment_id}, {order['id']}, {escape_str(warehouse)}, '{mode}', '{status}', '{tracking}', '{delivery_date.strftime('%Y-%m-%d')}');")
            shipment_id += 1
    
    append_sql("")
    append_sql("-- ============================================")
    append_sql("-- 9. REVIEWS (from Amazon TSV reviews)")
    append_sql("-- ============================================")
    
    reviews_db = []
    rev_id = 1
    
    tsv_dirs = [
        "amazon_reviews_us_Furniture_v1_00.tsv",
        "amazon_reviews_us_Gift_Card_v1_00.tsv",
        "amazon_reviews_us_Major_Appliances_v1_00.tsv",
    ]
    
    review_data = []
    
    for tsv_dir in tsv_dirs:
        dir_path = os.path.join(DATASET_DIR, tsv_dir)
        if os.path.isdir(dir_path):
            for f in os.listdir(dir_path):
                if f.endswith('.tsv') and len(review_data) < MAX_REVIEWS:
                    try:
                        df_tsv = pd.read_csv(os.path.join(dir_path, f), sep='\t', on_bad_lines='skip', nrows=300)
                        for _, row in df_tsv.iterrows():
                            if len(review_data) >= MAX_REVIEWS:
                                break
                            if pd.notna(row.get('review_body')):
                                star = row.get('star_rating', 5)
                                if pd.isna(star): star = 5
                                try: star = int(float(star))
                                except: star = 5
                                if star < 1 or star > 5: star = 5
                                
                                body = str(row['review_body'])[:1000]
                                review_data.append((star, body))
                    except Exception as e:
                        print(f"Skipping TSV {f}: {e}")
    
    if len(review_data) < MAX_REVIEWS // 2:
        print(f"Warning: Only found {len(review_data)} reviews from TSV files")
    
    user_pool = [3, 4, 10] + list(range(21, 41))
    
    for i, (star, content) in enumerate(review_data):
        if rev_id > MAX_REVIEWS:
            break
        user_id = random.choice(user_pool)
        if user_id > 40:
            user_id = random.choice([3, 4, 10, 21, 22, 23])
        product = random.choice(products_db) if products_db else {'id': 1}
        product_id = product['id']
        
        days_ago = random.randint(1, 365)
        created = (datetime.now() - timedelta(days=days_ago)).strftime('%Y-%m-%d %H:%M:%S')
        
        append_sql(f"INSERT INTO Reviews (id, user_id, product_id, star_rating, content, created_at) VALUES ({rev_id}, {user_id}, {product_id}, {star}, {escape_str(content)}, '{created}');")
        
        if random.random() < 0.25:
            reply = fake.sentence()[:200]
            reply_date = (datetime.now() - timedelta(days=random.randint(1, 180))).strftime('%Y-%m-%d %H:%M:%S')
            append_sql(f"UPDATE Reviews SET admin_reply = {escape_str(reply)}, reply_created_at = '{reply_date}' WHERE id = {rev_id};")
        
        reviews_db.append({'id': rev_id, 'product_id': product_id, 'star_rating': star})
        rev_id += 1
    
    append_sql("")
    append_sql("-- ============================================")
    append_sql("-- 10. STORE SETTINGS")
    append_sql("-- ============================================")
    
    currencies = ['TRY', 'USD', 'EUR']
    timezones = ['Europe/Istanbul', 'Europe/Ankara', 'Europe/Izmir']
    
    for i in range(1, 11):
        append_sql(f"INSERT INTO Store_Settings (store_id, email, category, description, currency, timezone) VALUES ({i}, {escape_str(f'store{i}@example.com')}, {escape_str(random.choice(list(categories.keys())) + ' Store')}, {escape_str(f'Official store setting for store {i}')}, '{random.choice(currencies)}', '{random.choice(timezones)}');")
    
    append_sql("")
    append_sql("-- ============================================")
    append_sql("-- 11. SYSTEM SETTINGS")
    append_sql("-- ============================================")
    
    system_settings = [
        ('platform_name', 'E-Commerce Platform', 'Platform display name'),
        ('commission_rate', '5.5', 'Default commission rate for stores'),
        ('min_payout_amount', '100.00', 'Minimum payout threshold'),
        ('max_return_days', '30', 'Maximum days for returns'),
        ('low_stock_threshold', '10', 'Alert threshold for low stock'),
        ('currency_default', 'TRY', 'Default currency code'),
        ('timezone_default', 'Europe/Istanbul', 'Default timezone'),
        ('maintenance_mode', 'false', 'System maintenance flag'),
        ('max_images_per_product', '8', 'Maximum product images'),
        ('session_timeout_minutes', '30', 'User session timeout'),
        ('review_approval_required', 'false', 'Require admin approval for reviews'),
        ('order_auto_cancel_days', '7', 'Days before auto-cancel pending orders'),
        ('shipping_default', 'STANDARD', 'Default shipping method'),
        ('tax_rate', '18', 'Default tax rate percentage'),
        ('max_quantity_per_order', '99', 'Maximum items per order'),
    ]
    
    sid = 1
    for key, value, desc in system_settings:
        append_sql(f"INSERT INTO SystemSettings (id, setting_key, setting_value, description) VALUES ({sid}, '{key}', '{value}', {escape_str(desc)});")
        sid += 1
    
    append_sql("")
    append_sql("-- ============================================")
    append_sql("-- 12. AUDIT LOGS")
    append_sql("-- ============================================")
    
    actions = [
        ('USER_LOGIN', 'INFO'), ('USER_LOGOUT', 'INFO'),
        ('PRODUCT_CREATED', 'INFO'), ('PRODUCT_UPDATED', 'INFO'),
        ('ORDER_PLACED', 'INFO'), ('ORDER_STATUS_CHANGED', 'INFO'),
        ('STORE_CREATED', 'INFO'), ('REVIEW_SUBMITTED', 'INFO'),
    ]
    
    actors = ['Admin User', 'Corporate User', 'System', 'User One', 'User Two']
    
    audit_id = 1
    for _ in range(300):
        action, severity = random.choice(actions)
        actor = random.choice(actors)
        
        entity_type = action.split('_')[0] if '_' in action else 'SYSTEM'
        entity_id = random.randint(1, 50) if random.random() > 0.3 else 'NULL'
        
        days_ago = random.randint(1, 90)
        created = (datetime.now() - timedelta(days=days_ago)).strftime('%Y-%m-%d %H:%M:%S')
        
        append_sql(f"INSERT INTO AuditLogs (id, actor, action, entity_type, entity_id, severity, created_at) VALUES ({audit_id}, {escape_str(actor)}, '{action}', '{entity_type}', {entity_id}, '{severity}', '{created}');")
        audit_id += 1
    
    output_path = os.path.join(BASE_DIR, 'init_db.sql')
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(sql_lines))
    
    print(f"\n{'='*60}")
    print("ETL COMPLETE!")
    print(f"{'='*60}")
    print(f"Users: {len(users)}")
    print(f"Customer Profiles: {profile_id - 1}")
    print(f"Stores: {len(store_names)}")
    print(f"Categories: {cat_id - 1}")
    print(f"Products: {len(products_db)}")
    print(f"Orders: {len(orders_db)}")
    print(f"Order Items: {oi_id - 1}")
    print(f"Shipments: {shipment_id - 1}")
    print(f"Reviews: {len(reviews_db)}")
    print(f"Store Settings: 10")
    print(f"System Settings: {sid - 1}")
    print(f"Audit Logs: {audit_id - 1}")
    print(f"{'='*60}")
    print(f"Output: {output_path}")

if __name__ == '__main__':
    generate_db_script()